name: CI
on: pull_request
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1
            - uses: actions/setup-go@v2-beta
              with:
                go-version: '^1.13.1'
            - name: Install CI check
              run: go get github.com/windmilleng/tilt-extensions-ci && go install github.com/windmilleng/tilt-extensions-ci
            - name: Running tests
              run: echo $PATH && echo $GOPATH && tilt-extensions-ci tilt-extensions
